version: '3.8'
services:
  postgres:
    env_file:
      - ./.env-prod

  knowledge-base-backend:
    image:  knowledge-base-backend:latest
    container_name:  knowledge-base-backend
    hostname:  knowledge-base-backend
    build:
      context: .
      dockerfile: ./dockerfile
    restart: always
    ports:
      - 5000:5000
    expose:
      - 5000
    env_file:
      - ./.env-prod
    depends_on:
      - postgres
    # external_links:
    #   - postgres:postgres
    networks:
      - knowledge_base
    external_links:
      - postgres:postgres

networks:
  knowledge_base:
    name: knowledge_base
    driver: bridge
