version: '3.8'
services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:14.2-alpine
    restart: always
    ports:
      - 5435:5432
    expose:
      - '5435'
    networks:
      - knowledge_base
    environment:
      PGDATA: /var/lib/postgresql/data/postgres-data/
    volumes:
      - ./models/db/postgres-schema.sql:/docker-entrypoint-initdb.d/db.sql
      - ./:/var/lib/postgresql/data

networks:
  knowledge_base:
    name: knowledge_base
    driver: bridge
